version: '3.3'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - ./configs/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    env_file:
      - ./configs/.env
    command: ["sh", "-c", "redis-server --save 60 1 --loglevel warning --requirepass \"$REDIS_PASSWORD\""]
    volumes:
      - redis_data:/data
    networks:
      - backend_net

  backend:
    build: .
    container_name: backend_go_app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./configs/.env
    depends_on:
      - db
      - redis
    networks:
      - backend_net

volumes:
  postgres_data:
  redis_data:

networks:
  backend_net:
    driver: bridge
