# 示例：配置多个 S3 存储
# 运行方式: docker-compose -f docker-compose.multi-s3.yml up -d
version: '3.3'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db_s3
    restart: always
    env_file:
      - ./configs/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net

  redis:
    image: redis:7-alpine
    container_name: redis_cache_s3
    restart: always
    env_file:
      - ./configs/.env
    command: ["sh", "-c", "redis-server --save 60 1 --loglevel warning --requirepass \"$REDIS_PASSWORD\""]
    volumes:
      - redis_data:/data
    networks:
      - backend_net

  backend:
    build: .
    container_name: backend_go_app_s3
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./configs/.env
    depends_on:
      - db
      - redis
    networks:
      - backend_net

volumes:
  postgres_data:
  redis_data:

networks:
  backend_net:
    driver: bridge
