version: '3.8'

services:
  backend-all-in-one:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-all-services
    ports:
      - "1000:1000"  # SSH端口
      - "1001:1001"  # 后端API端口
    volumes:
      - postgres_data:/var/lib/postgresql
      - redis_data:/var/lib/redis
      - uploads_data:/app/uploads
    environment:
      - PORT=1001
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=backend
      - DB_SSLMODE=disable
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - JWT_SECRET=your-very-secret-jwt-key-change-this-in-production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  uploads_data:
    driver: local 