# 示例：配置多个本地存储
# 运行方式: docker-compose -f docker-compose.multi-local.yml up -d
version: '3.3'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db_local
    restart: always
    env_file:
      - ./configs/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net

  redis:
    image: redis:7-alpine
    container_name: redis_cache_local
    restart: always
    env_file:
      - ./configs/.env
    command: ["sh", "-c", "if [ -z \"$$REDIS_PASSWORD\" ]; then echo 'ERROR: REDIS_PASSWORD is empty'; exit 1; fi; exec redis-server --save 60 1 --loglevel warning --requirepass \"$$REDIS_PASSWORD\""]
    volumes:
      - redis_data:/data
    networks:
      - backend_net

  backend:
    build: .
    container_name: backend_go_app_local
    restart: always
    ports:
      - "8080:8080"
      - "1234:1234"
    env_file:
      - ./configs/.env
    depends_on:
      - db
      - redis
    volumes:
      # 将主机上的目录挂载到容器中，以持久化本地上传的文件
      - ./uploads/docs:/app/uploads/docs
      - ./uploads/avatars:/app/uploads/avatars
      # 如果使用了自定义路径，需要对应修改挂载点:
      # - ./custom_avatars:/app/custom_avatar_path
    networks:
      - backend_net

volumes:
  postgres_data:
  redis_data:

networks:
  backend_net:
    driver: bridge
