version: '3.3'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    command: redis-server --save 60 1 --loglevel warning --requirepass myredispassword
    volumes:
      - redis_data:/data
    networks:
      - backend_net

  backend:
    build: .
    container_name: backend_go_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: backend
      DB_SSLMODE: disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: myredispassword
      REDIS_DB: 0
    depends_on:
      - db
      - redis
    networks:
      - backend_net

volumes:
  postgres_data:
  redis_data:

networks:
  backend_net:
    driver: bridge
